ExceptionPropagationCatcher
Endpoint Catcher;

Catcher
{
    Endpoint endpt;

    Public Function addEndpoint(Endpoint endpt_ref)
    {
        endpt = endpt_ref;
    }

    Public Function testPropagateNetworkExceptionOnEndpointCall() returns TrueFalse
    {
        TrueFalse caught = False;
        try {
            endpt.testPropagateException();
        }
        catch (NetworkException as err) {
            caught = True;
        }
        return caught;
    }
}
